// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	uuid "github.com/satori/go.uuid"
	"time"
)

type Login struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type NewPost struct {
	Title string `json:"title"`
	Body  string `json:"body"`
}

type NewUser struct {
	Email       string    `json:"email"`
	FirstName   string    `json:"firstname"`
	LastName    string    `json:"lastname"`
	Password    string    `json:"password"`
}

type Post struct {
	ID    string `json:"user_id"`
	Title string `json:"title"`
	Body  string `json:"body"`
	User  *User  `json:"user"`
}

type RefreshTokenInput struct {
	Token string `json:"token"`
}

type User struct {
	UserID   uuid.UUID `json:"user_id"`
	Email       string    `json:"email"`
	FirstName   string    `json:"firstname"`
	LastName    string    `json:"lastname"`
	Password    string    `json:"password"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}
